In [2]:
options(warn = -1)
options(repr.plot.width = 15, repr.plot.height = 9)
Sys.setlocale(category = "LC_ALL",locale = "ko_KR.UTF-8") # 한글 쓰려면 이 세개는 무조건 쓰고 들어가야 한다

[1] "ko_KR.UTF-8/ko_KR.UTF-8/ko_KR.UTF-8/C/ko_KR.UTF-8/C.UTF-8"

#### 조건문

In [ ]:
x <-  10
y <- runif(1) * 100

if(x > y){
    print("x > runif()")
    print("x가 큽니다.")
}else if(x < y){
    print("x < runif()")
    print("x가 작습니다.")
}else{
    print("x = runif()")
    print("x와 같습니다.")
}

[1] "x < runif()"
[1] "x가 작습니다."

#### 홀짝수 구분

In [7]:
a <- 8 
if(a%%1 == 0){
    cat(a, "는 짝수 입니다.\n")
}else{
    cat(a, "는 홀수 입니다.\n")
}

8 는 짝수 입니다.

In [9]:
a <- c(8, 10, 11) 
ifelse(a%%2 == 0, "짝수","홀수")

[1] "짝수" "짝수" "홀수"

In [11]:
a <- c(8, 10, 11) 
ifelse(a%%2 == 0, paste(a,":짝수"),paste(a,":홀수"))

[1] "8 :짝수"  "10 :짝수" "11 :홀수"

#### readline

In [13]:
num1 <- as.integer(readline("숫자를 입력하세요:")) # 파이썬에서 input
num1
class(num1)

[1] 11

[1] "integer"

In [ ]:
# 사용자로부터 점수를 입력 받아 학점으로 변경하여 출력하기


score <- as.integer(readline("학점을 입력하세요:"))

if(score >= 90){
    cat(score, "점은 A학점 입니다.\n")
}else if(score >= 80){
    cat(score, "점은 B학점 입니다.\n")
}else if(score >= 70){
    cat(score, "점은 C학점 입니다.\n")
}else if(score >= 60){
    cat(score, "점은 D학점 입니다.\n")
}else{
    cat(score, "점은 F학점 입니다.\n")
}

22 점은 F학점 입니다.

In [18]:
score <- as.integer(readline("점수를 입력하세요: "))

grade <- if (score >= 90) {
    "A"
} else if (score >= 80) {
    "B"
} else if (score >= 70) {
    "C"
} else if (score >= 60) {
    "D"
} else {
    "F"
}

cat(score, "점은", grade, "학점 입니다.\n")

55 점은 F 학점 입니다.

In [ ]:
score <- as.integer(readline("점수를 입력하세요: "))
ifelse(score%%2 == 0, paste(a,":짝수"),paste(a,":홀수"))

33 점은 F 학점 입니다.

In [20]:
# csv file 불러 처리
excel <- read.csv("../Data/excel.csv")
head(excel)

  q1 q2 q3 q4 q5
1 2  4  4  2  2
2 1  2  2  2  2
3 2  3  4  3  3
4 3  5  5  3  3
5 3  2  4  4  4
6 4  3  3  4  2

In [21]:
str(excel)

'data.frame':	402 obs. of  5 variables:
 $ q1: int  2 1 2 3 3 4 3 4 4 4 ...
 $ q2: int  4 2 3 5 2 3 4 2 4 2 ...
 $ q3: int  4 2 4 5 4 3 4 4 5 4 ...
 $ q4: int  2 2 3 3 4 4 2 4 3 2 ...
 $ q5: int  2 2 3 3 4 2 2 4 4 3 ...

In [24]:
# q1 컬럼으로 Data가 3보다 크거나 같으면 data의 제곱근을 구하고 아니면 원래 Data 출력하기
excel$q1 >3
ifelse(excel$q1 >=3, paste(sqrt(excel$q1)),paste(excel$q1))

  [1] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE
 [13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE
 [25] FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE
 [37]  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE
 [49]  TRUE FALSE  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
 [61]  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
 [73] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
 [85] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE
 [97]  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE
[109]  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
[121] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
[133] FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE
[145] FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
[157] FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[169] FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
[181]  TRUE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
[193] FALSE  TRUE FALSE  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE
[205] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE
[217] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE
[229] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE
[241] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
[253] FALSE  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE
[265] FALSE FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
[277] FALSE FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
[289] FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE  TRUE FALSE  TRUE
[301] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE
[313] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE
[325] FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE
[337]  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[349] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE
[361] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE  TRUE FALSE
[373]  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE
[385] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE
[397] FALSE  TRUE FALSE FALSE FALSE FALSE

  [1] "2"                "1"                "2"
  [4] "1.73205080756888" "1.73205080756888" "2"
  [7] "1.73205080756888" "2"                "2"
 [10] "2"                "2"                "1.73205080756888"
 [13] "1.73205080756888" "1.73205080756888" "1"
 [16] "1.73205080756888" "1.73205080756888" "1.73205080756888"
 [19] "2"                "1.73205080756888" "1.73205080756888"
 [22] "2"                "2"                "2"
 [25] "1.73205080756888" "2"                "2"
 [28] "2"                "1.73205080756888" "1.73205080756888"
 [31] "1"                "1.73205080756888" "1.73205080756888"
 [34] "1.73205080756888" "2"                "1.73205080756888"
 [37] "2"                "2"                "1.73205080756888"
 [40] "2"                "2"                "2"
 [43] "1.73205080756888" "1.73205080756888" "2"
 [46] "2"                "2"                "1"
 [49] "2"                "1.73205080756888" "2"
 [52] "2"                "1.73205080756888" "2"
 [55] "1.73205080756888" "2"                "2"
 [58] "2"                "2"                "1.73205080756888"
 [61] "2"                "2"                "2"
 [64] "1.73205080756888" "1.73205080756888" "1.73205080756888"
 [67] "1.73205080756888" "2"                "1"
 [70] "2"                "1.73205080756888" "1.73205080756888"
 [73] "1.73205080756888" "2"                "2"
 [76] "2"                "1"                "1.73205080756888"
 [79] "1.73205080756888" "2"                "2"
 [82] "2"                "1.73205080756888" "2"
 [85] "1.73205080756888" "1.73205080756888" "2"
 [88] "1.73205080756888" "2"                "2"
 [91] "2"                "2"                "2"
 [94] "2"                "1"                "2"
 [97] "2"                "2"                "2"
[100] "2"                "1.73205080756888" "1.73205080756888"
[103] "2"                "1.73205080756888" "1.73205080756888"
[106] "2"                "2"                "2"
[109] "2"                "2"                "2"
[112] "2"                "1.73205080756888" "2"
[115] "2"                "2"                "1.73205080756888"
[118] "1.73205080756888" "1.73205080756888" "2"
[121] "1"                "1.73205080756888" "2"
[124] "1.73205080756888" "1.73205080756888" "2"
[127] "1.73205080756888" "1.73205080756888" "1.73205080756888"
[130] "2"                "2"                "2"
[133] "1"                "1.73205080756888" "1.73205080756888"
[136] "2"                "1.73205080756888" "2"
[139] "1.73205080756888" "1"                "2"
[142] "1.73205080756888" "2.23606797749979" "2"
[145] "1.73205080756888" "1.73205080756888" "2"
[148] "2"                "1.73205080756888" "2"
[151] "1.73205080756888" "1.73205080756888" "1"
[154] "1.73205080756888" "2"                "2"
[157] "1.73205080756888" "1.73205080756888" "2"
[160] "2"                "2"                "2"
[163] "2"                "2"                "1.73205080756888"
[166] "1.73205080756888" "1.73205080756888" "2"
[169] "2"                "2"                "1"
[172] "1.73205080756888" "1.73205080756888" "2"
[175] "1.73205080756888" "2"                "1.73205080756888"
[178] "1"                "2"                "1.73205080756888"
[181] "2.23606797749979" "2"                "1.73205080756888"
[184] "1.73205080756888" "2"                "2"
[187] "1.73205080756888" "2"                "1.73205080756888"
[190] "1.73205080756888" "1"                "1.73205080756888"
[193] "2"                "2"                "2"
[196] "2"                "2"                "2"
[199] "2"                "1.73205080756888" "2"
[202] "2"                "2"                "1.73205080756888"
[205] "1.73205080756888" "1.73205080756888" "2"
[208] "1"                "1.73205080756888" "2"
[211] "1.73205080756888" "1.73205080756888" "2"
[214] "1.73205080756888" "1.73205080756888" "1"
[217] "1.73205080756888" "1.73205080756888" "2"
[220] "1.73205080756888" "2"                "1.73205080756888"
[223] "1"                "2"                "1.73205080756888"
[226] "2.23606797749979" "2"                "1.73205080756888"
[229] "1.73205080756888" "2"                "2"
[232] "1.73205080756888" "2"                "1.73205080756888"
[235] "1.73205080756888" "1"                "1.73205080756888"
[238] "2"                "2"                "1.73205080756888"
[241] "1.73205080756888" "2"                "2"
[244] "2"                "2"                "2"
[247] "2"                "1.73205080756888" "1"
[250] "1.73205080756888" "2"                "2"
[253] "2"                "2"                "2"
[256] "2"                "2"                "1.73205080756888"
[259] "2"                "2"                "2"
[262] "1.73205080756888" "1.73205080756888" "1.73205080756888"
[265] "2"                "1"                "1.73205080756888"
[268] "2"                "1.73205080756888" "1.73205080756888"
[271] "2"                "2"                "1.73205080756888"
[274] "2"                "1.73205080756888" "1.73205080756888"
[277] "1"                "1.73205080756888" "2"
[280] "2"                "1.73205080756888" "1.73205080756888"
[283] "2"                "2"                "2"
[286] "2"                "2"                "2"
[289] "1.73205080756888" "1"                "1.73205080756888"
[292] "2"                "2"                "2"
[295] "2"                "2"                "2"
[298] "2"                "1.73205080756888" "2"
[301] "2"                "2"                "1.73205080756888"
[304] "1.73205080756888" "1.73205080756888" "2"
[307] "1"                "1.73205080756888" "1.73205080756888"
[310] "2"                "2"                "1.73205080756888"
[313] "2"                "1.73205080756888" "1.73205080756888"
[316] "1"                "1.73205080756888" "2"
[319] "2"                "1.73205080756888" "1.73205080756888"
[322] "2"                "2"                "2"
[325] "2"                "2"                "2"
[328] "1.73205080756888" "1"                "1.73205080756888"
[331] "2"                "2"                "2"
[334] "2"                "2"                "2"
[337] "2"                "1.73205080756888" "2"
[340] "2"                "2"                "1.73205080756888"
[343] "1.73205080756888" "1.73205080756888" "2"
[346] "1"                "2"                "1.73205080756888"
[349] "1.73205080756888" "1"                "1.73205080756888"
[352] "2"                "2"                "1.73205080756888"
[355] "1.73205080756888" "2"                "2"
[358] "2"                "2"                "2"
[361] "2"                "1.73205080756888" "1"
[364] "1.73205080756888" "2"                "2"
[367] "2"                "2"                "2"
[370] "2"                "2"                "1.73205080756888"
[373] "2"                "2"                "2"
[376] "1.73205080756888" "1.73205080756888" "1.73205080756888"
[379] "2"                "1"                "1.73205080756888"
[382] "2"                "1.73205080756888" "1.73205080756888"
[385] "2"                "2"                "1.73205080756888"
[388] "2"                "1.73205080756888" "1.73205080756888"
[391] "1"                "1.73205080756888" "2"
[394] "2"                "1.73205080756888" "1.73205080756888"
[397] "2"                "2"                "2"
[400] "2"                "2"                "2"

In [27]:
# 선생님 정답
q1 <- excel$q1
length(q1)
excel$q6 <- ifelse(q1 >= 3, sqrt(q1), q1) # 새롭게 만들어서 넣어줌
head(excel)

[1] 402

  q1 q2 q3 q4 q5 q6
1 2  4  4  2  2  2.000000
2 1  2  2  2  2  1.000000
3 2  3  4  3  3  2.000000
4 3  5  5  3  3  1.732051
5 3  2  4  4  4  1.732051
6 4  3  3  4  2  2.000000

In [ ]:
# score가 80점 이상이면 우수, 아니면 노력 이라고 출력하기 _예제
scores = c(78, 85, 95, 65, 100)
ifelse(scores >= 80, "우수", "노력")

[1] "노력" "우수" "우수" "노력" "우수"