#### 문장의 유사도 분석
: 두 개의 문장이 비슷한 것인지 또는 관련이 있는지 분석
- 레벤슈타인 거리
- N-gram
- 코사인 유사도
- 유클리언 유사도 
- 맨하튼 유사도

----
#### 레벤슈타인 거리(Lvenshtein distance)
- 두 개의 문자열이 어느 정도 다른지를 나타내는 것으로 편집 거리(Edit Distance)라고도 부르다.
- 의학 분야에서는 DNA 배열의 유사성을 판단할 떄도 사용.

In [3]:
from lvenshtein import Lvenshtein
lv = Lvenshtein() # 인스턴스 하나 만들어서 이렇게 씀

In [4]:
# 함수 잘 도는 지 테스트
print(lv.calc_distance("가나다라","가마바라")) # 틀린 거리를 보여줌

2

In [5]:
# 신촌역과 가장 근접한 순서로 정렬

samples = ['신발', '마곡역', '신천역', '신천군', '신촌역']
base = samples[4] # 기준값을 줘야 함 _ 신촌역을 기준값으로 줌

r = sorted(samples, key= lambda n: lv.calc_distance(base, n))

for n in r:
    print(lv.calc_distance(base, n), n) # 기준이랑 틀린 갯수를 알려줌

0 신촌역
1 신천역
2 신발
2 마곡역
2 신천군

---
#### N-gram 유사도
- 이웃한 N개의 문자     
- 서로 다른 2개의 문장을 N-gram으로 비교해보면 출현하는 단어의 종류와 빈도가 확인가능   
- 논문 도용 등을 확인

In [6]:
from ngram import Ngram
ngram = Ngram()

In [7]:
# 2문장(gram) 나누기
a = "오늘 강남에서 맛있는 스파게티를 먹었다."
b= "강남에서 먹었던 오늘의 스파게티는 맛있었다."
print(ngram.ngram(a,2))
print(ngram.ngram(b,2))

['오늘', '늘 ', ' 강', '강남', '남에', '에서', '서 ', ' 맛', '맛있', '있는', '는 ', ' 스', '스파', '파게', '게티', '티를', '를 ', ' 먹', '먹었', '었다', '다.']
['강남', '남에', '에서', '서 ', ' 먹', '먹었', '었던', '던 ', ' 오', '오늘', '늘의', '의 ', ' 스', '스파', '파게', '게티', '티는', '는 ', ' 맛', '맛있', '있었', '었다', '다.']

In [8]:
# 3문장으로 나누기
print(ngram.ngram(a,3))
print(ngram.ngram(b,3))

['오늘 ', '늘 강', ' 강남', '강남에', '남에서', '에서 ', '서 맛', ' 맛있', '맛있는', '있는 ', '는 스', ' 스파', '스파게', '파게티', '게티를', '티를 ', '를 먹', ' 먹었', '먹었다', '었다.']
['강남에', '남에서', '에서 ', '서 먹', ' 먹었', '먹었던', '었던 ', '던 오', ' 오늘', '오늘의', '늘의 ', '의 스', ' 스파', '스파게', '파게티', '게티는', '티는 ', '는 맛', ' 맛있', '맛있었', '있었다', '었다.']

In [9]:
# 유사도 비교

r2 = ngram.diff_ngram(a, b, 2)
print("2gram 유사도 :", r2)

r3 = ngram.diff_ngram(a, b, 3)
print("3gram 유사도 :", r3)

2gram 유사도 : (0.7619047619047619, ['오늘', '강남', '남에', '에서', '서 ', ' 맛', '맛있', '는 ', ' 스', '스파', '파게', '게티', ' 먹', '먹었', '었다', '다.'])
3gram 유사도 : (0.45, ['강남에', '남에서', '에서 ', ' 맛있', ' 스파', '스파게', '파게티', ' 먹었', '었다.'])

In [10]:
# 퀴즈
a = "머신러닝은 매우 재미있는 기술이라 공부하고 있습니다."
b = "공부하면 재미있는 기술이라 머신러닝을 배우고 있습니다."

ex2 = ngram.diff_ngram(a, b, 2)
print("2gram 유사도 :", ex2)

ex3 = ngram.diff_ngram(a, b, 3)
print("3gram 유사도 :", ex3)

2gram 유사도 : (0.75, ['머신', '신러', '러닝', ' 재', '재미', '미있', '있는', '는 ', ' 기', '기술', '술이', '이라', '라 ', '공부', '부하', '고 ', ' 있', '있습', '습니', '니다', '다.'])
3gram 유사도 : (0.6296296296296297, ['머신러', '신러닝', ' 재미', '재미있', '미있는', '있는 ', '는 기', ' 기술', '기술이', '술이라', '이라 ', '공부하', '고 있', ' 있습', '있습니', '습니다', '니다.'])

In [11]:
a = "본문과 전혀 관계 없는 내용이지만 마시멜로는 맛있습니다."
b = "마시멜로는 본문과 전혀 관계 없이 맛있습니다."

ex2 = ngram.diff_ngram(a, b, 2)
print("2gram 유사도 :", ex2)

ex3 = ngram.diff_ngram(a, b, 3)
print("3gram 유사도 :", ex3)

2gram 유사도 : (0.7333333333333333, ['본문', '문과', '과 ', ' 전', '전혀', '혀 ', ' 관', '관계', '계 ', ' 없', '는 ', '마시', '시멜', '멜로', '로는', '는 ', ' 맛', '맛있', '있습', '습니', '니다', '다.'])
3gram 유사도 : (0.6206896551724138, ['본문과', '문과 ', '과 전', ' 전혀', '전혀 ', '혀 관', ' 관계', '관계 ', '계 없', '마시멜', '시멜로', '멜로는', '로는 ', ' 맛있', '맛있습', '있습니', '습니다', '니다.'])

In [12]:
a = "파이썬 프로그래밍에서 중요한 것은 블록 입니다."
b = "겨울에는 충분한 수분을 보충해야 합니다."

ex2 = ngram.diff_ngram(a, b, 2)
print("2gram 유사도 :", ex2)

ex3 = ngram.diff_ngram(a, b, 3)
print("3gram 유사도 :", ex3) # 유사도가 거의 없음을 확인

2gram 유사도 : (0.12, ['한 ', '니다', '다.'])
3gram 유사도 : (0.041666666666666664, ['니다.'])

In [13]:
# 보통은 2gram가지고 많이 한다

----
#### 코사인(cosine) 유사도
: 두 문장을 비교하여 유사도 측정

In [14]:
a = "머신러닝은 매우 재미있는 기술이라 공부하고 있습니다."
b = "공부하면 재미있는 기술이라 머신러닝을 배우고 있습니다."

from sklearn.feature_extraction.text import TfidfVectorizer
sentences = (a, b)

tfid_vectorizer = TfidfVectorizer()
sentences

('머신러닝은 매우 재미있는 기술이라 공부하고 있습니다.', '공부하면 재미있는 기술이라 머신러닝을 배우고 있습니다.')

In [15]:
# 문장 벡터화(숫자 만들기) 하기 (어휘사전 만들기)

In [16]:
# 문장 벡터화 하기 (어휘 사전 만들기)
tfid_matrix = tfid_vectorizer.fit_transform(sentences)

In [17]:
### 코사인 유사도 
from sklearn.metrics.pairwise import cosine_similarity

# 첫번째 문장과 두번째 문장 비교 
cos_similar = cosine_similarity(tfid_matrix[0],tfid_matrix[1])
print('코사인 유사도 :',cos_similar) # 코사인 유사도 0.33이면 되게높은거다

코사인 유사도 : [[0.33609693]]

In [18]:
a = "머신러닝은 매우 재미있는 기술이라 공부하고 있습니다."
b = "공부하면 재미있는 기술이라 머신러닝을 배우고 있습니다 "

tfid_matrix.toarray()

array([[0.47042643, 0.        , 0.33471228, 0.47042643, 0.47042643,
        0.        , 0.        , 0.33471228, 0.33471228],
       [0.        , 0.47042643, 0.33471228, 0.        , 0.        ,
        0.47042643, 0.47042643, 0.33471228, 0.33471228]])

In [19]:
a = "나는 빨간색 딸기 좋아한다."
b = "나는 빨간색 체리 좋아한다."
c = "나는 빨간색 딸기 빨간색 딸기 좋아한다."


sentences = (a, c)

tfid_vectorizer = TfidfVectorizer()
tfid_matrix = tfid_vectorizer.fit_transform(sentences)
cos_similar = cosine_similarity(tfid_matrix[0], tfid_matrix[1])
cos_similar

array([[0.9486833]])

---
#### 유사도를 이용한 추천 시스템 구현
: 코사인 유사도만으로 영화의 줄거리에 기반하여 영화를 추천하는 추천 시스템 구축

In [20]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [21]:
data = pd.read_csv('../Data/movies_metadata.csv',low_memory=False)
data

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [22]:
data.head(2)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0

In [23]:
data.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='str')

> 코사인 유사도에 사용할 데이터는 영화 제목에 해당하는 title, 줄거리에 해당하는 overview
좋아하는 영화를 입력하면 해당 영화의 줄거리와 유사한 줄거리의 영화를 찾아서 추천하는 시스템을 만들 것 입니다.

In [24]:
data[['title', 'overview']].head()

,title,overview
0,Toy Story,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...

In [25]:
data.shape

(45466, 24)

In [26]:
# # 상위 2만개의 샘플
# data = data.head(20000)

In [27]:
# overview에 결측치 _ 항상 확인해야 함
data['overview'].isnull().sum()

np.int64(954)

In [28]:
# 결측치를 빈값으로 대체
data['overview'] = data['overview'].fillna('')

In [29]:
tfidf = TfidfVectorizer(stop_words='english')
tfid_matrix = tfidf.fit_transform(data['overview'])
tfid_matrix.shape

(45466, 75827)

In [30]:
cosine_sim = cosine_similarity(tfid_matrix, tfid_matrix) # 반복문이 일어난다_ 같은거 두개 집어 넣음
print("코사인 유사도 연관 결과 :", cosine_sim.shape)

코사인 유사도 연관 결과 : (45466, 45466)

In [32]:
# 기존 데이터프레임으로 부터 영화의 타이틀을 key 영화의 인덱스를 value로 하는 딕셔너리 
title_to_index = dict(zip(data['title'],data.index))
idx = title_to_index['Father of the Bride Part II']
print(idx)
# 영화의 제목을 추천할거라 타이틀이 키가 된다

4

In [33]:
# 선택한 영화의 제목을 입력하면 코사인 유사도를 통해 overview가 유사한 10개의 영화를 찾아내는 함수

def get_recommendations(title, cosine_sim=cosine_sim):
    # 선택한 영화의 타이틀로 부터 해당 영화의 인덱스를 받아 온다.
    idx = title_to_index[title]

    # 해당 영화와 모든 영화와의 유사도를 가져온다
    sim_scores = list(enumerate(cosine_sim[idx]))

    # 유사도에 따라 영화들을 정렬한다.
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # 가장 유사한 10개의 영화를 받아온다.
    sim_scores = sim_scores[1:11]

    # 가장 유사한 10개의 영화의 인덱스를 얻는다.
    movie_indices = [idx[0] for idx in sim_scores]

    # 가장 유사한 10개의 영화의 제목을 리턴한다.
    return data['title'].iloc[movie_indices]

In [41]:
# 영화 다크 나이트 라이즈의 overview가 유사한 영화
get_recommendations('The Dark Knight Rises')
get_recommendations('Toy Story')

15348                                     Toy Story 3
2997                                      Toy Story 2
10301                          The 40 Year Old Virgin
24523                                       Small Fry
23843                     Andy Hardy's Blonde Trouble
29202                                      Hot Splash
43427                Andy Kaufman Plays Carnegie Hall
38476    Superstar: The Life and Times of Andy Warhol
42721    Andy Peters: Exclamation Mark Question Point
8327                                        The Champ
Name: title, dtype: str